/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BenvenutoRouteImport } from './routes/benvenuto'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RischiRouteImport } from './routes/rischi'
import { Route as TerminiRouteImport } from './routes/termini'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenvenutoRoute = BenvenutoRouteImport.update({
  id: '/benvenuto',
  path: '/benvenuto',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RischiRoute = RischiRouteImport.update({
  id: '/rischi',
  path: '/rischi',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benvenuto': typeof BenvenutoRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/privacy': typeof PrivacyRoute
  '/rischi': typeof RischiRoute
  '/termini': typeof TerminiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benvenuto': typeof BenvenutoRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/privacy': typeof PrivacyRoute
  '/rischi': typeof RischiRoute
  '/termini': typeof TerminiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benvenuto': typeof BenvenutoRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/privacy': typeof PrivacyRoute
  '/rischi': typeof RischiRoute
  '/termini': typeof TerminiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/benvenuto' | '/cookie-policy' | '/privacy' | '/rischi' | '/termini'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/benvenuto' | '/cookie-policy' | '/privacy' | '/rischi' | '/termini'
  id:
    | '__root__'
    | '/'
    | '/benvenuto'
    | '/cookie-policy'
    | '/privacy'
    | '/rischi'
    | '/termini'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenvenutoRoute: typeof BenvenutoRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  PrivacyRoute: typeof PrivacyRoute
  RischiRoute: typeof RischiRoute
  TerminiRoute: typeof TerminiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benvenuto': {
      id: '/benvenuto'
      path: '/benvenuto'
      fullPath: '/benvenuto'
      preLoaderRoute: typeof BenvenutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rischi': {
      id: '/rischi'
      path: '/rischi'
      fullPath: '/rischi'
      preLoaderRoute: typeof RischiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenvenutoRoute: BenvenutoRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  PrivacyRoute: PrivacyRoute,
  RischiRoute: RischiRoute,
  TerminiRoute: TerminiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
